"""Initial migration with all tables

Revision ID: 56bb1bbb1636
Revises:
Create Date: 2025-12-21 15:23:38.679438

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56bb1bbb1636"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_departments_code"), "departments", ["code"], unique=True)
    op.create_index(op.f("ix_departments_id"), "departments", ["id"], unique=False)
    op.create_table(
        "product_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column(
            "efficiency_multiplier", sa.DECIMAL(precision=5, scale=2), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_categories_code"), "product_categories", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_product_categories_id"), "product_categories", ["id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "weekly_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("num_workers", sa.Integer(), nullable=True),
        sa.Column("work_days_per_week", sa.Integer(), nullable=True),
        sa.Column("hours_per_day", sa.DECIMAL(precision=4, scale=2), nullable=True),
        sa.Column(
            "total_planned_hours",
            sa.DECIMAL(precision=10, scale=2),
            sa.Computed(
                "num_workers * work_days_per_week * hours_per_day",
            ),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("week_number", "year", name="uq_weekly_plan"),
    )
    op.create_index(op.f("ix_weekly_plans_id"), "weekly_plans", ["id"], unique=False)
    op.create_index(
        op.f("ix_weekly_plans_week_number"),
        "weekly_plans",
        ["week_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_plans_year"), "weekly_plans", ["year"], unique=False
    )
    op.create_table(
        "efficiency_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "period_type",
            sa.Enum("DAILY", "WEEKLY", "MONTHLY", name="efficiencyperiodtype"),
            nullable=False,
        ),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("week_number", sa.Integer(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "planned_work_hours", sa.DECIMAL(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "actual_work_hours", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("total_std_time", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column(
            "total_target_time", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("efficiency_actual", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("efficiency_target", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("num_workers", sa.Integer(), nullable=True),
        sa.Column("num_work_days", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_efficiency_summaries_date"),
        "efficiency_summaries",
        ["date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_efficiency_summaries_id"), "efficiency_summaries", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_efficiency_summaries_week_number"),
        "efficiency_summaries",
        ["week_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_efficiency_summaries_year"),
        "efficiency_summaries",
        ["year"],
        unique=False,
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_number", sa.String(length=50), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column(
            "full_name",
            sa.String(length=255),
            sa.Computed(
                "first_name || ' ' || last_name",
            ),
            nullable=True,
        ),
        sa.Column("primary_department_id", sa.Integer(), nullable=True),
        sa.Column("hire_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["primary_department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employees_employee_number"),
        "employees",
        ["employee_number"],
        unique=True,
    )
    op.create_index(op.f("ix_employees_id"), "employees", ["id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_number", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_code", sa.String(length=50), nullable=True),
        sa.Column(
            "standard_time_minutes", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["category_code"],
            ["product_categories.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(
        op.f("ix_products_item_number"), "products", ["item_number"], unique=True
    )
    op.create_table(
        "work_phases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("department_id", "code", name="uq_department_phase"),
    )
    op.create_index(op.f("ix_work_phases_id"), "work_phases", ["id"], unique=False)
    op.create_table(
        "bom_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("material_code", sa.String(length=100), nullable=False),
        sa.Column("material_name", sa.String(length=255), nullable=True),
        sa.Column("quantity", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bom_items_id"), "bom_items", ["id"], unique=False)
    op.create_table(
        "production_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_number", sa.String(length=100), nullable=False),
        sa.Column("reference_number", sa.String(length=100), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("ship_date", sa.Date(), nullable=True),
        sa.Column("week_number", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("current_department_id", sa.Integer(), nullable=True),
        sa.Column("queue_position", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["current_department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_production_orders_id"), "production_orders", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_production_orders_order_number"),
        "production_orders",
        ["order_number"],
        unique=True,
    )
    op.create_index(
        op.f("ix_production_orders_reference_number"),
        "production_orders",
        ["reference_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_orders_week_number"),
        "production_orders",
        ["week_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_orders_year"), "production_orders", ["year"], unique=False
    )
    op.create_table(
        "efficiency_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("efficiency_summary_id", sa.Integer(), nullable=False),
        sa.Column("production_order_id", sa.Integer(), nullable=True),
        sa.Column("quantity_completed", sa.Integer(), nullable=True),
        sa.Column("quantity_target", sa.Integer(), nullable=True),
        sa.Column(
            "standard_time_minutes", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("actual_std_time", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("target_std_time", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["efficiency_summary_id"], ["efficiency_summaries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["production_order_id"],
            ["production_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_efficiency_items_id"), "efficiency_items", ["id"], unique=False
    )
    op.create_table(
        "order_department_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("production_order_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                "OVER_QUANTITY",
                name="orderstatusenum",
            ),
            nullable=True,
        ),
        sa.Column("quantity_completed", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["production_order_id"], ["production_orders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "production_order_id", "department_id", name="uq_order_department"
        ),
    )
    op.create_index(
        op.f("ix_order_department_status_id"),
        "order_department_status",
        ["id"],
        unique=False,
    )
    op.create_table(
        "order_phase_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("production_order_id", sa.Integer(), nullable=False),
        sa.Column("work_phase_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["production_order_id"], ["production_orders.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["work_phase_id"],
            ["work_phases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "production_order_id", "work_phase_id", name="uq_order_phase"
        ),
    )
    op.create_index(
        op.f("ix_order_phase_values_id"), "order_phase_values", ["id"], unique=False
    )
    op.create_table(
        "production_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_uuid", sa.UUID(), nullable=True),
        sa.Column("production_order_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("work_phase_id", sa.Integer(), nullable=True),
        sa.Column("batch_uuid", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("ended_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "duration_minutes",
            sa.Integer(),
            sa.Computed(
                "EXTRACT(EPOCH FROM (ended_at - started_at)) / 60",
            ),
            nullable=True,
        ),
        sa.Column(
            "quantity_completed", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["production_order_id"], ["production_orders.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["work_phase_id"],
            ["work_phases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_production_tasks_batch_uuid"),
        "production_tasks",
        ["batch_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_tasks_id"), "production_tasks", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_production_tasks_task_uuid"),
        "production_tasks",
        ["task_uuid"],
        unique=True,
    )
    op.create_table(
        "weekly_plan_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("weekly_plan_id", sa.Integer(), nullable=False),
        sa.Column("production_order_id", sa.Integer(), nullable=False),
        sa.Column("planned_sequence", sa.Integer(), nullable=True),
        sa.Column("estimated_hours", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["production_order_id"],
            ["production_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["weekly_plan_id"], ["weekly_plans.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "weekly_plan_id", "production_order_id", name="uq_plan_order"
        ),
    )
    op.create_index(
        op.f("ix_weekly_plan_items_id"), "weekly_plan_items", ["id"], unique=False
    )
    # ### end Alembic commands ###
    # Partial unique indexes for efficiency_summaries
    op.execute(
        """
        CREATE UNIQUE INDEX uq_efficiency_daily 
        ON efficiency_summaries (period_type, department_id, date, year)
        WHERE period_type = 'DAILY'
    """
    )

    op.execute(
        """
        CREATE UNIQUE INDEX uq_efficiency_weekly 
        ON efficiency_summaries (period_type, department_id, week_number, year)
        WHERE period_type = 'WEEKLY'
    """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop partial unique indexes
    op.execute("DROP INDEX IF EXISTS uq_efficiency_weekly")
    op.execute("DROP INDEX IF EXISTS uq_efficiency_daily")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weekly_plan_items_id"), table_name="weekly_plan_items")
    op.drop_table("weekly_plan_items")
    op.drop_index(op.f("ix_production_tasks_task_uuid"), table_name="production_tasks")
    op.drop_index(op.f("ix_production_tasks_id"), table_name="production_tasks")
    op.drop_index(op.f("ix_production_tasks_batch_uuid"), table_name="production_tasks")
    op.drop_table("production_tasks")
    op.drop_index(op.f("ix_order_phase_values_id"), table_name="order_phase_values")
    op.drop_table("order_phase_values")
    op.drop_index(
        op.f("ix_order_department_status_id"), table_name="order_department_status"
    )
    op.drop_table("order_department_status")
    op.drop_index(op.f("ix_efficiency_items_id"), table_name="efficiency_items")
    op.drop_table("efficiency_items")
    op.drop_index(op.f("ix_production_orders_year"), table_name="production_orders")
    op.drop_index(
        op.f("ix_production_orders_week_number"), table_name="production_orders"
    )
    op.drop_index(
        op.f("ix_production_orders_reference_number"), table_name="production_orders"
    )
    op.drop_index(
        op.f("ix_production_orders_order_number"), table_name="production_orders"
    )
    op.drop_index(op.f("ix_production_orders_id"), table_name="production_orders")
    op.drop_table("production_orders")
    op.drop_index(op.f("ix_bom_items_id"), table_name="bom_items")
    op.drop_table("bom_items")
    op.drop_index(op.f("ix_work_phases_id"), table_name="work_phases")
    op.drop_table("work_phases")
    op.drop_index(op.f("ix_products_item_number"), table_name="products")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_employees_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_employee_number"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(
        op.f("ix_efficiency_summaries_year"), table_name="efficiency_summaries"
    )
    op.drop_index(
        op.f("ix_efficiency_summaries_week_number"), table_name="efficiency_summaries"
    )
    op.drop_index(op.f("ix_efficiency_summaries_id"), table_name="efficiency_summaries")
    op.drop_index(
        op.f("ix_efficiency_summaries_date"), table_name="efficiency_summaries"
    )
    op.drop_table("efficiency_summaries")
    op.drop_index(op.f("ix_weekly_plans_year"), table_name="weekly_plans")
    op.drop_index(op.f("ix_weekly_plans_week_number"), table_name="weekly_plans")
    op.drop_index(op.f("ix_weekly_plans_id"), table_name="weekly_plans")
    op.drop_table("weekly_plans")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_product_categories_id"), table_name="product_categories")
    op.drop_index(op.f("ix_product_categories_code"), table_name="product_categories")
    op.drop_table("product_categories")
    op.drop_index(op.f("ix_departments_id"), table_name="departments")
    op.drop_index(op.f("ix_departments_code"), table_name="departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
